# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('expresult', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='test name')),
                ('requirement', models.CharField(blank=True, max_length=200, null=True, verbose_name='requirements')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('stepdesc', models.CharField(blank=True, max_length=200, null=True, verbose_name='step description')),
                ('stepexpresult', models.CharField(blank=True, max_length=200, null=True, verbose_name='step expresult')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('steps', models.ManyToManyField(blank=True, to='cqtest.Step')),
            ],
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
