# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cqtest', '0002_auto_20170411_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='steps',
        ),
    ]
