# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqtest', '0004_test_tokenised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='tokenised',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='tokens'),
        ),
    ]
